Fix #62: MimeType NoClassDefFoundError
See
https://stackoverflow.com/questions/16570523/getresourceasstream-returns-null;
the two fixes are

  - call the class' `getResourceAsStream()` instead of the ClassLoader's
  - use an absolute path to get the resource.

Passes `mvn test` here.